### ISSUE TITLE
Salida práctico 6

### ISSUE THREAD

**Issue by jaarac** [juliangiletta/vision2020#1]
Ingrese el angulo de rotacion expresado en grados sexagesimal: 20
Ingrese la traslacion en x: 20
Ingrese la traslacion en y: 20
Ingrese el factor de escala: .5

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-c66161798a91> in <module>
     14         s = input('Ingrese el factor de escala: ')
     15         (h, w) = (s*img_rec.shape[0], s*img_rec.shape[1])
---> 16         new_img = transf_similaridad(img_rec, tx, ty, angle, h, w, s)
     17         cv2.imwrite('resultado1.png', new_img)
     18         cv2.imshow('Resultado', new_img)

<ipython-input-8-773ac1b09dc5> in transf_similaridad(image, tx, ty, angle_grad, h, w, s)
      1 def transf_similaridad(image, tx, ty, angle_grad, h, w, s):
      2 
----> 3     angle_rad = angle_grad * np.pi/180
      4 
      5     M = np.float32([[s*np.cos(angle_rad), s*np.sin(angle_rad), tx],

TypeError: can't multiply sequence by non-int of type 'float'

**Comment by juliangiletta** [comment]
Corrección realizada.
